name = "SparseArraysBase"
uuid = "0d5efcca-f356-4864-8770-e1ed8d78f208"
version = "0.9.5"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
FunctionImplementations = "7c7cc465-9c6a-495f-bdd1-f42428e86d0c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
MapBroadcast = "ebd9b9da-f48d-417c-9660-449667d60261"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[compat]
Accessors = "0.1.41"
FunctionImplementations = "0.4"
Random = "1.10"
ArrayLayouts = "1.11"
LinearAlgebra = "1.10"
TypeParameterAccessors = "0.4.3"
GPUArraysCore = "0.2"
SparseArrays = "1.10"
TensorAlgebra = "0.6.2, 0.7"
julia = "1.10"
MapBroadcast = "0.1.5"
Dictionaries = "0.4.3"
NamedDimsArrays = "0.13, 0.14"
FillArrays = "1.13"
Adapt = "4.3"

[weakdeps]
NamedDimsArrays = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"

[extensions]
SparseArraysBaseNamedDimsArraysExt = "NamedDimsArrays"
SparseArraysBaseTensorAlgebraExt = ["TensorAlgebra", "SparseArrays"]
